version: '3.9'

services:
  app:
    image: node:16.15.1
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: dokcer_vue
    ports:
      - 5173:5173
    working_dir: /usr/src/app
    volumes:
      - ./vue-project:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
